#Multistage build
FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

#Copy csproj and do restore
COPY *.csproj ./
RUN dotnet restore

#Copy everything and build
COPY . ./
RUN dotnet build -c Release
RUN dotnet publish -c Release -o out

#Build runtime image

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet","aspnetapp.dll"]